### ISSUE TITLE
Error while import rrdtool on Debian Jessie

### ISSUE THREAD

**Issue by diraol** [commx/python-rrdtool#16]
Hi,

I've installed the rrdtool on a virtualenv (python 3.4) and when I try to import it I get the error below:
```
In [1]: import rrdtool
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-71e14b967e40> in <module>()
----> 1 import rrdtool

ImportError: .../lib/python3.4/site-packages/rrdtool.cpython-34m.so: undefined symbol: rrd_fetch_cb_register
```

If you need any other information, please ask me.

**Comment by commx** [comment]
Hi, please try installing `pip install rrdtool==0.1.6` for the time being, as >=0.1.7 requires rrdtool 1.5.0 which isn't in Debian Jessie's packages. Since `librrd-dev` does not ship any headers that disclose the rrdtool version, I'm not able to add contextual checks which excludes the fetch callback functions for rrdtool <1.5.0.

**Comment by diraol** [comment]
Thanks @commx , that really solved my problem.
