### ISSUE TITLE
any advices that we can use it in windows ?

### ISSUE THREAD

**Issue by zhnglicho** [commx/python-rrdtool#30]
now it only supports linux, how can we use it in windows ? thanks

**Comment by commx** [comment]
Hi,

in the very beginning of the project (2012), I've also built Windows binaries of the package. After that time, I only provided source packages which can be used to build binaries on Linux and macOS.

Building it on Windows is way more complicated, because you'll need to build all the dependencies on your own as the precompiled library versions on gnome.org are too old; rrdtool uses functions that were introduced in later versions. I took some time to create a current build for Python 3.7 (amd64), which required some manual changes in the code as Windows has no support for the `localtime_r` function. You can download the build artifact [here](http://www.commx.ws/dl/python-rrdtool/python-rrdtool-0.1.15-win-amd64-py37.zip). To use it, extract it into your site-packages folder (%LOCALAPPDATA%\Programs\Python\Python37\lib\site-packages) and then you should be able to import the rrdtool module.

To build in your own, you'll need a recent Visual Studio installation. First grab vcpkg and build/install all the dependencies (see WIN32-TIPS-AND-TRICKS in rrdtool upstream distribution). Compile librrd for your desired target architecture and make sure that the dependencies are in the correct place. Copy the resulting library files into a copy of python-rrdtool source. Define localtime_r alias for localtime_s and run python setup.py install. This is not straightforward and I'm rarely using Windows these days, so some things could be done easier for sure.

**Comment by zhnglicho** [comment]
Thanks , this information is very useful to me, I will try.
