### ISSUE TITLE
[0.1.15] "import rrdtool" fails with: undefined symbol: rrd_xport

### ISSUE THREAD

**Issue by hartwork** [commx/python-rrdtool#35]
Importing `python-rrdtool` crashes on my with the following error:
```console
# cd "$(mktemp -d)"
# virtualenv --python=python3.7 py37
# source py37/bin/activate
# pip install rrdtool==0.1.15
# python -c 'import rrdtool'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /tmp/tmp.a7JJOSEC25/py37/lib/python3.7/site-packages/rrdtool.cpython-37m-x86_64-linux-gnu.so: undefined symbol: rrd_xport
```
Happens with:
 - Python version: 2.7, 3.7
 - RRDtool version: 1.6.0, 1.7.2
 - python-rrdtool version: 0.1.15

Is this a known problem?

**Comment by commx** [comment]
Weird. Which OS do you use? If you have the chance, look up the librrd library and check if it exports the rrd_xport function using `nm -D /path/to/librrd.so | grep rrd_xport`

In my case (Debian "buster" 10.3, librrd-dev 1.7.1-2):

```
# nm -D /usr/lib/x86_64-linux-gnu/librrd.so | grep rrd_xport
0000000000025990 T rrd_xport
```

In fact, rrd_xport is there since at least rrdtool 1.2, so it looks like there is something wrong with your librrd installation. Feel free to post the output of `nm -D /path/to/librrd.so`

**Comment by hartwork** [comment]
Hi @commx thanks for your reply! It seems like my `librdd.so` lacks that symbol because it was configured with `--disable-rrd_graph`. I have enforced use of `--enabled-rrd_graph` now and `python -c 'import rrdtool'` no longer crashes with the symptoms shown earlier. Sorry for the noise! :pray:
